# 创建一个文件夹存放rocketmq-exporter实例信息
- name: Create dir
  file:
    path: /usr/local/prometheus/groups/rocketmq_exporter
    state: directory

# 添加rocketmq_exporter地址文件
- name: 
  template:
    src: rocketmq.j2
    dest: /usr/local/prometheus/groups/rocketmq_exporter/{{ hostvars[item].inventory_hostname }}.json
  with_items: "{{ groups['rocketmq_exporter'] }}"

# 修改prometheus配置文件
- name:
  blockinfile:
    path: /usr/local/prometheus/prometheus.yml
    marker: '  # {mark} rocketmq_exporter'
    block: |2
        - job_name: "rocketmq_exporter"
          file_sd_configs:
          - files:
              - /usr/local/prometheus/groups/rocketmq_exporter/*.json

# 重启prometheus
- name: Start prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: yes
