# 创建一个文件夹存放各主机信息
- name: Create dir
  file:
    path: /usr/local/prometheus/groups/redis_exporter
    state: directory

# 添加redis_exporter地址文件
- name: 
  template:
    src: redis_exporter.j2
    dest: /usr/local/prometheus/groups/redis_exporter/redis-{{ item.0 }}.json
  with_together: 
    - "{{ hostvars[groups['redis_exporter'][0]]['redis_cluster_ports'] }}"
    - "{{ hostvars[groups['redis_exporter'][0]]['redis_exporter_ports'] }}"

# 修改prometheus配置文件
- name:
  blockinfile:
    path: /usr/local/prometheus/prometheus.yml
    marker: '  # {mark} redis_exporter'
    block: |2
        - job_name: "redis_exporter"
          file_sd_configs:
          - files:
              - /usr/local/prometheus/groups/redis_exporter/*.json

# 重启prometheus
- name: Start prometheus service
  service:
    name: prometheus
    state: restarted
    enabled: yes