# 创建一个目录保存所有的exporter
- name: Create a directory to save all exporter
  file:
    path: /usr/local/monitor
    state: directory

# 解压redis_exporter的二进制包
- name: Unarchive the redis_exporter package
  unarchive: 
    src: redis_exporter-v{{ redis_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/monitor/

# 重命名redis_exporter安装目录
- name: Rename the path of redis_exporter
  shell: mv /usr/local/monitor/redis_exporter-v{{ redis_exporter_version }}.linux-amd64 /usr/local/monitor/redis_exporter

# 生成Systemd Service文件
- name: Add systemd script
  template:
    src: systemd.j2
    dest: /etc/systemd/system/redis_exporter_{{ item.0 }}.service
  with_together:
    - "{{ redis_cluster_ports }}"
    - "{{ redis_exporter_ports }}"

# systemctl daemon-reload
- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

# 启动redis_exporter
- name: Start redis_exporter service
  service:
    name: "redis_exporter_{{ item }}"
    state: restarted
    enabled: yes
  with_items: "{{ redis_cluster_ports }}"
