# 创建一个目录保存所有的exporter
- name: Create a directory to save all exporter
  file:
    path: /usr/local/monitor
    state: directory

# 解压node_exporter的二进制包
- name: Unarchive the node_exporter package
  unarchive: 
    src: node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/monitor/

# 重命名node_exporter安装目录
- name: Rename the path of node_exporter
  shell: mv /usr/local/monitor/node_exporter-{{ node_exporter_version }}.linux-amd64 /usr/local/monitor/node_exporter

# 创建node_exporter日志目录，并做好软链接
- name: Create log path for node_exporter
  file:
   path: /data/monitor/node_exporter/logs
   state: directory

- name: Create logs link
  file:
    path: /usr/local/monitor/node_exporter/logs
    src: /data/monitor/node_exporter/logs
    state: link

# 添加启动脚本
- name: Add a script for launcher
  template:
    src: start_script.j2
    dest: /usr/local/monitor/node_exporter/launcher.sh
    mode: 0755

# 添加systemd脚本
- name: Add systemd script
  template:
    src: node_service.j2
    dest: /etc/systemd/system/node_exporter.service

# systemctl daemon-reload
- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

# node_exporter
- name: Start node_exporter service
  service:
    name: node_exporter
    state: restarted
    enabled: yes

