# 创建一个目录保存所有的exporter
- name: Create a directory to save all exporter
  file:
    path: /usr/local/monitor
    state: directory

# 解压node_exporter的二进制包
- name: Unarchive the node_exporter package
  unarchive: 
    src: node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /usr/local/monitor/

# 重命名node_exporter安装目录
- name: Rename the path of node_exporter
  shell: mv /usr/local/monitor/node_exporter-{{ node_exporter_version }}.linux-amd64 /usr/local/monitor/node_exporter

# 添加systemd脚本
- name: Add systemd script
  template:
    src: systemd.j2
    dest: /etc/systemd/system/node_exporter.service

# systemctl daemon-reload
- name: Reload systemd daemon
  systemd:
    daemon-reload: yes

# node_exporter
- name: Start node_exporter service
  service:
    name: node_exporter
    state: restarted
    enabled: yes